AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for Batches Group
Resources:
  BatchesLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: batches
      Role:
        arn:aws:iam::855430746673:role/caliber-mobile-cf
      Code:
        ImageUri: !Join ["/",[!Join [".",[!Sub "${AWS::AccountId}", "dkr", "ecr", !Sub "${AWS::Region}", "amazonaws", "com"]], "batches-lambda:latest"]]
      Timeout: 5
      PackageType: "Image"

