AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BatchLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs14.x
      Content:
        S3Bucket: caliber-batches
        S3Key: BatchesLayersCode
      Description: BatchesLayersCode
      LayerName: batches-layers
  Batches:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Batches
      Handler: lambda/index.handler
      Layers:
        - !Ref BatchLayer
      Role:
        Fn::GetAtt:
          - BatchesRole
          - Arn
      Code:
        S3Bucket: caliber-batches
        S3Key: BatchesCode
      Runtime: nodejs14.x
      Timeout: 5
  BatchesRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: BatchesRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: AmazonS3FullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource:
                  - 'arn:aws:s3:::exchange-data-raw'
                  - 'arn:aws:s3:::exchange-data-raw/*'
