AWSTemplateFormatVersion: 2010-09-09
Description: ECR repo for categories lambda
Resources:
  CategoryECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "categories-lambda"
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only two untagged images, expire all others",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "imageCountMoreThan",
                  "countNumber": 2
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
Outputs:
  BatchesECRArn:
    Value: !GetAtt categoriesECR.Arn
    Export:
      Name: categoriesECRArn